
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dculncdvxlaatruzgktr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdWxuY2R2eGxhYXRydXpna3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzYwMDAsImV4cCI6MjA1ODcxMjAwMH0.NJr6WEJlS6VESyigPeag5HBXg1Ne6XZGuiLM8xUbXSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
