// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumkdhpcbizjsztheqho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bWtkaHBjYml6anN6dGhlcWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTQ1MTgsImV4cCI6MjA1ODQ3MDUxOH0.CE1_Umca0K8MBtAC1Qyu6e6KCPv81MPzZ-g54tplv-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);