
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbrfwjjlpgeuobknyfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icmZ3ampscGdldW9ia255ZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTE2MjEsImV4cCI6MjA1ODc4NzYyMX0.RQedSfnYIiv98wReLCXZk1_cf9Eg5I5fq5TO66dzZ-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
